---
title: "ME_2"
author: "Ziheng Zhong"
format: pdf
editor: visual
---

## Initialization

```{r}
install.packages("janitor")
library("janitor")

install.packages("knitr")
library("knitr")

install.packages("lubridate")
library("lubridate")

install.packages("opendatatoronto")
library("opendatatoronto")

install.packages("tidyverse")
library("tidyverse")
```

## Git Check

```{r}
use_git_config(
  user.name = "iJustinn",
  user.email = "ijustinzhong@gmail.com"
)
```

## Processing Data

```{r}
Tickets_data <-
  read_csv(
    file = "Tickets_Issued.csv",
    show_col_types = FALSE
  )
```

```{r}
head(Tickets_data)
```

```{r}
Tickets_data <-
  clean_names(Tickets_data)

head(Tickets_data)
```

```{r}
Tickets_data <-
  Tickets_data |>
  select(
    offence_year,
    division
  )

head(Tickets_data)
```

```{r}
names(Tickets_data)
```

```{r}
Tickets_data$offence_year |>
  unique()
```

```{r}
Tickets_data$division |>
  unique()
```

```{r}
Tickets_data |>
  count(division)
```

```{r}
Tickets_data |>
  ggplot(aes(x = division)) +
  geom_bar() +
  theme_minimal() + 
  labs(x = "Division", y = "Number of Tickets") 
```

```{r}
Tickets_data |>
  ggplot(aes(x = offence_year)) +
  geom_bar() +
  theme_minimal() + 
  labs(x = "Year", y = "Number of Tickets") 
```
