---
title: "Toronto_Police_Annual_Ticket_Issued"
author: "Ziheng Zhong"
format: pdf
editor: visual
---

Upon examining the traffic ticket data issued across various divisions over several years, we discerned notable patterns in distribution and frequency. The data, sourced from "Tickets_Issued.csv," was processed using R to focus on the key variables of 'offence_year' and 'division'. Our bar chart for 'offence_year' displayed a consistent volume of tickets issued annually, suggesting steady traffic enforcement activity without significant fluctuations or anomalies. Conversely, the 'division' bar chart exhibited a heterogeneous distribution, with certain divisions like D32 and D41 showing a markedly higher incidence of tickets, potentially indicating traffic congestion or stricter enforcement protocols in those areas.

These visualizations, crafted through ggplot2's minimalist theme, provided a clear and concise representation of the data. The year-on-year consistency in ticket issuance implies a stable traffic situation or enforcement policy, while the variation among divisions could be attributed to a myriad of factors, such as urban development, enforcement policy changes, or even reporting practices. These insights lay the groundwork for more granular analysis, perhaps scrutinizing the underlying causes of the disparities among divisions or assessing the impact of traffic law amendments over time.
